/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.softlab.efr.services.auth.controllers;

import ru.softlab.efr.services.auth.exchange.model.ErrorData;
import ru.softlab.efr.services.auth.exchange.model.MotivationSettings;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.validation.BindingResult;
import org.springframework.data.web.PageableDefault;
import org.springframework.data.domain.*;

import java.util.*;

import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * the MotivationCheckSettings API
 */
public interface MotivationCheckSettingsApi {

    /**
     * Запрос получения настроек программы мотивации   
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/auth/v1/settings/motivation-config",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<MotivationSettings> getMotivationCheckSettings() throws Exception;



    /**
     * Запрос обновления настроек программы мотивации 
     * @param updateMotivationSettingsRq Тело запроса обновления настроек программы мотивации  
     * @return Экземпляр класса {@link ResponseEntity}
     * @throws Exception исключение, выбрасываемое в случае ошибок при выполнении метода
     */
    @RequestMapping(value = "/auth/v1/settings/motivation-config",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> updateMotivationCheckSettings(@Valid @RequestBody MotivationSettings updateMotivationSettingsRq) throws Exception;


}
